const languages=['pl','en','nl','de','fr','es'];
export const rows={
  title:['Akcja ratunkowa','Rescue mission','Reddingsmissie','Rettungsmission','Mission de sauvetage','Misión de rescate'],
  start:['GRAJ FABUŁĘ','PLAY THE STORY','SPEEL HET VERHAAL','GESCHICHTE SPIELEN','JOUER L’HISTOIRE','JUGAR LA HISTORIA'],
  resume:['KONTYNUUJ FABUŁĘ','CONTINUE THE STORY','VERHAAL HERVATTEN','GESCHICHTE FORTSETZEN','CONTINUER L’HISTOIRE','CONTINUAR LA HISTORIA'],
  brief:['Motorówka. Brak paliwa. Tajemnica wyspy.','A motorboat. Low fuel. An island secret.','Een motorboot. Weinig brandstof. Een eilandgeheim.','Ein Motorboot. Wenig Treibstoff. Ein Inselgeheimnis.','Un bateau à moteur. Peu de carburant. Un secret sur l’île.','Una lancha. Poco combustible. Un secreto en la isla.'],
  local:['Fabuła solo • zapis na tym urządzeniu','Solo story • saved on this device','Solo verhaal • opgeslagen op dit apparaat','Solo-Geschichte • auf diesem Gerät gespeichert','Histoire solo • enregistrée sur cet appareil','Historia individual • guardada en este dispositivo'],
  menu:['Cel i sterowanie','Objective and controls','Doel en besturing','Ziel und Steuerung','Objectif et commandes','Objetivo y controles'],
  back:['Wróć do gry','Back to the game','Terug naar het spel','Zurück zum Spiel','Retour au jeu','Volver al juego'],
  exit:['Wróć do menu','Return to menu','Terug naar het menu','Zurück zum Menü','Retour au menu','Volver al menú'],
  camera:['Kamera','Camera','Camera','Kamera','Caméra','Cámara'],
  view:['Widok','View','Beeld','Ansicht','Vue','Vista'],
  map:['Mapa sześciu wysp','Map of six islands','Kaart van zes eilanden','Karte der sechs Inseln','Carte des six îles','Mapa de seis islas'],
  first:['Oczami postaci','First person','Eerste persoon','Ich-Perspektive','Première personne','Primera persona'],
  third:['Zza postaci','Third person','Derde persoon','Dritte Person','Troisième personne','Tercera persona'],
  saved:['Fabuła zapisana','Story saved','Verhaal opgeslagen','Geschichte gespeichert','Histoire enregistrée','Historia guardada'],
  unsaved:['Zapis niedostępny na tym urządzeniu','Saving unavailable on this device','Opslaan niet beschikbaar op dit apparaat','Speichern auf diesem Gerät nicht verfügbar','Enregistrement indisponible sur cet appareil','Guardado no disponible en este dispositivo'],
  controls:['WASD / strzałki / drążek: ruch. E / DZIAŁAJ: interakcja. Spacja / ATAK: strzał. Przeciąganie / Q i R / prawy drążek: kamera.','WASD / arrows / stick: move. E / ACTION: interact. Space / ATTACK: shoot. Drag / Q and R / right stick: camera.','WASD / pijlen / stick: bewegen. E / ACTIE: interactie. Spatie / AANVAL: schieten. Slepen / Q en R / rechterstick: camera.','WASD / Pfeile / Stick: bewegen. E / AKTION: interagieren. Leertaste / ANGRIFF: schießen. Ziehen / Q und R / rechter Stick: Kamera.','WASD / flèches / stick : déplacement. E / ACTION : interaction. Espace / ATTAQUE : tir. Glisser / Q et R / stick droit : caméra.','WASD / flechas / palanca: moverse. E / ACCIÓN: interactuar. Espacio / ATAQUE: disparar. Arrastrar / Q y R / palanca derecha: cámara.'],
  intro:['Paliwo na rezerwie. Dopłyń do pomostu na głównej wyspie i użyj DZIAŁAJ.','Fuel is low. Reach the main island pier and use ACTION.','De brandstof is bijna op. Vaar naar de steiger op het hoofdeiland en gebruik ACTIE.','Der Tank ist fast leer. Fahre zum Steg der Hauptinsel und nutze AKTION.','Le réservoir est presque vide. Rejoignez le ponton de l’île principale et utilisez ACTION.','Queda poco combustible. Llega al muelle de la isla principal y usa ACCIÓN.'],
  'dock-goal':['Dopłyń do pomostu po paliwo.','Reach the pier for fuel.','Vaar naar de steiger voor brandstof.','Fahre zum Steg zum Tanken.','Rejoignez le ponton pour faire le plein.','Llega al muelle para repostar.'],
  'fuel-goal':['Zatankuj przy dystrybutorze.','Refuel at the pump.','Tank bij de pomp.','Tanke an der Zapfsäule.','Faites le plein à la pompe.','Reposta en el surtidor.'],
  'cave-goal':['Popłyń na wyspę dżungli i zbadaj jaskinię.','Sail to Jungle Island and explore the cave.','Vaar naar het jungle-eiland en verken de grot.','Fahre zur Dschungelinsel und erkunde die Höhle.','Naviguez vers l’île de la jungle et explorez la grotte.','Navega a la isla de la jungla y explora la cueva.'],
  'paper-goal':['Odsuń gazetę ze stołu.','Move the newspaper on the table.','Schuif de krant op de tafel weg.','Schiebe die Zeitung auf dem Tisch weg.','Déplacez le journal sur la table.','Aparta el periódico de la mesa.'],
  'gun-goal':['Podnieś ukryty pistolet.','Pick up the hidden pistol.','Pak het verborgen pistool.','Nimm die versteckte Pistole.','Ramassez le pistolet caché.','Recoge la pistola escondida.'],
  'exit-cave-goal':['Wyjdź z jaskini i wróć do motorówki.','Leave the cave and return to the boat.','Verlaat de grot en keer terug naar de boot.','Verlasse die Höhle und kehre zum Boot zurück.','Sortez de la grotte et retournez au bateau.','Sal de la cueva y vuelve a la lancha.'],
  'estate-goal':['Zbadaj strzeżoną rezydencję na skalistej wyspie.','Investigate the guarded estate on Fortress Island.','Onderzoek het bewaakte landhuis op het rotseiland.','Untersuche das bewachte Anwesen auf der Felseninsel.','Explorez la résidence gardée sur l’île rocheuse.','Investiga la residencia vigilada en la isla rocosa.'],
  'boss-goal':['Pokonaj bossa i znajdź klucz do piwnicy.','Defeat the boss and find the cellar key.','Versla de baas en vind de keldersleutel.','Besiege den Boss und finde den Kellerschlüssel.','Vainquez le chef et trouvez la clé de la cave.','Vence al jefe y encuentra la llave del sótano.'],
  'key-goal':['Zabierz klucz pozostawiony przez bossa.','Collect the key left by the boss.','Pak de sleutel die de baas achterliet.','Nimm den Schlüssel des Bosses.','Ramassez la clé laissée par le chef.','Recoge la llave que dejó el jefe.'],
  'cellar-goal':['Otwórz przejście do piwnicy.','Unlock the cellar passage.','Open de doorgang naar de kelder.','Öffne den Weg zum Keller.','Ouvrez le passage vers la cave.','Abre el paso al sótano.'],
  'people-goal':['Uwolnij wszystkie osoby z cel.','Free everyone from the cells.','Bevrijd iedereen uit de cellen.','Befreie alle Personen aus den Zellen.','Libérez toutes les personnes des cellules.','Libera a todas las personas de las celdas.'],
  'escort-goal':['Wyprowadź uratowanych z rezydencji.','Escort the rescued people out of the estate.','Begeleid de geredde mensen uit het landhuis.','Begleite die Geretteten aus dem Anwesen.','Faites sortir les personnes sauvées de la résidence.','Saca a las personas rescatadas de la residencia.'],
  'boat-goal':['Zaprowadź grupę do motorówki i wsiądź.','Take the group to the boat and board.','Breng de groep naar de boot en stap aan boord.','Bring die Gruppe zum Boot und steige ein.','Conduisez le groupe au bateau et embarquez.','Lleva al grupo a la lancha y sube a bordo.'],
  'home-goal':['Wróć z uratowanymi do głównej przystani.','Return with the rescued people to the main harbor.','Breng de geredde mensen terug naar de hoofdhaven.','Kehre mit den Geretteten zum Haupthafen zurück.','Ramenez les personnes sauvées au port principal.','Vuelve con las personas rescatadas al puerto principal.'],
  complete:['Misja ukończona! Pięć osób bezpiecznie wróciło na wyspę.','Mission complete! Five people returned safely to the island.','Missie voltooid! Vijf mensen zijn veilig terug op het eiland.','Mission erfüllt! Fünf Personen sind sicher zurück auf der Insel.','Mission accomplie ! Cinq personnes sont revenues sur l’île en sécurité.','¡Misión cumplida! Cinco personas han vuelto a salvo a la isla.'],
  dock:['Zacumuj i wysiądź','Dock and disembark','Aanmeren en uitstappen','Anlegen und aussteigen','Accoster et débarquer','Atracar y desembarcar'],
  boat:['Wsiądź do motorówki','Board the motorboat','Stap in de motorboot','Steige ins Motorboot','Monter dans le bateau','Subir a la lancha'],
  'board-group':['Zabierz grupę na pokład','Bring the group aboard','Neem de groep aan boord','Nimm die Gruppe an Bord','Faire embarquer le groupe','Embarcar al grupo'],
  refuel:['Zatankuj','Refuel','Tanken','Tanken','Faire le plein','Repostar'],
  'enter-cave':['Wejdź do jaskini','Enter the cave','De grot in','Höhle betreten','Entrer dans la grotte','Entrar en la cueva'],
  'move-paper':['Odsuń gazetę','Move the newspaper','Krant verschuiven','Zeitung wegschieben','Déplacer le journal','Apartar el periódico'],
  'take-gun':['Weź pistolet','Take the pistol','Pistool pakken','Pistole nehmen','Prendre le pistolet','Recoger la pistola'],
  supplies:['Uzupełnij zapasy','Replenish supplies','Voorraad aanvullen','Vorräte auffüllen','Refaire les provisions','Reponer suministros'],
  'leave-cave':['Wyjdź z jaskini','Leave the cave','Grot verlaten','Höhle verlassen','Sortir de la grotte','Salir de la cueva'],
  'enter-estate':['Wejdź do rezydencji','Enter the estate','Landhuis betreden','Anwesen betreten','Entrer dans la résidence','Entrar en la residencia'],
  'leave-estate':['Wyjdź z rezydencji','Leave the estate','Landhuis verlaten','Anwesen verlassen','Sortir de la résidence','Salir de la residencia'],
  'take-key':['Zabierz klucz','Take the key','Sleutel pakken','Schlüssel nehmen','Prendre la clé','Recoger la llave'],
  cellar:['Zejdź do piwnicy','Go down to the cellar','Naar de kelder','In den Keller gehen','Descendre dans la cave','Bajar al sótano'],
  upstairs:['Wróć na górę','Go upstairs','Naar boven','Nach oben gehen','Remonter','Subir'],
  'free-person':['Otwórz celę','Open the cell','Cel openen','Zelle öffnen','Ouvrir la cellule','Abrir la celda'],
  empty:['Brak amunicji. Zapasy są w jaskini i skrzyniach na wyspach.','No ammunition. Supplies are in the cave and island caches.','Geen munitie. Voorraad ligt in de grot en in kisten op de eilanden.','Keine Munition. Vorräte findest du in der Höhle und Inselkisten.','Plus de munitions. Des provisions se trouvent dans la grotte et les caisses des îles.','Sin munición. Hay suministros en la cueva y en las cajas de las islas.'],
  closer:['Podejdź bliżej oznaczonego celu.','Move closer to the marked objective.','Ga dichter naar het gemarkeerde doel.','Gehe näher an das markierte Ziel.','Approchez de l’objectif indiqué.','Acércate al objetivo marcado.'],
  checkpoint:['Wracasz do przystani. Misja i uratowani są zachowani.','You return to the harbor. Mission progress and rescues are kept.','Je keert terug naar de haven. Missievoortgang en reddingen blijven bewaard.','Du kehrst zum Hafen zurück. Fortschritt und Rettungen bleiben erhalten.','Vous revenez au port. La progression et les sauvetages sont conservés.','Vuelves al puerto. Se conservan el progreso y los rescates.'],
  paddle:['Brak paliwa. Motorówkę nadal można powoli doprowadzić do pomostu.','No fuel. You can still move the boat slowly to a pier.','Geen brandstof. Je kunt de boot nog langzaam naar een steiger brengen.','Kein Treibstoff. Du kannst das Boot noch langsam zum Steg bewegen.','Plus de carburant. Vous pouvez encore amener lentement le bateau à un ponton.','Sin combustible. Todavía puedes llevar la lancha lentamente a un muelle.'],
  'under-fire':['Ochroniarze atakują. Wyceluj lub wycofaj się.','The guards are attacking. Aim or retreat.','De bewakers vallen aan. Richt of trek je terug.','Die Wachen greifen an. Ziele oder zieh dich zurück.','Les gardes attaquent. Visez ou reculez.','Los guardias atacan. Apunta o retírate.'],
  hit:['Trafienie','Hit','Geraakt','Treffer','Touché','Impacto'],
  'guard-down':['Przeciwnik pokonany','Opponent defeated','Tegenstander verslagen','Gegner besiegt','Adversaire vaincu','Rival derrotado'],
  supplied:['Zapasy uzupełnione','Supplies replenished','Voorraad aangevuld','Vorräte aufgefüllt','Provisions renouvelées','Suministros repuestos'],
  home:['Główna wyspa','Main Island','Hoofdeiland','Hauptinsel','Île principale','Isla principal'],
  jungle:['Wyspa dżungli','Jungle Island','Jungle-eiland','Dschungelinsel','Île de la jungle','Isla de la jungla'],
  fortress:['Skalista wyspa','Fortress Island','Rotseiland','Felseninsel','Île rocheuse','Isla rocosa'],
  highlands:['Górska wyspa','Highlands Island','Bergeiland','Berginsel','Île montagneuse','Isla montañosa'],
  smugglers:['Wyspa przemytników','Smugglers Island','Smokkelaars-eiland','Schmugglerinsel','Île des contrebandiers','Isla de contrabandistas'],
  paradise:['Rajska wyspa','Paradise Island','Paradijseiland','Paradiesinsel','Île paradisiaque','Isla paradisíaca']
};
const aliases={docked:'fuel-goal',tanked:'cave-goal',cave:'paper-goal',paper:'gun-goal',gun:'estate-goal',
  'estate-hint':'estate-goal',estate:'boss-goal',key:'cellar-goal','cellar-hint':'cellar-goal',
  'need-gun':'cave-goal','boss-first':'boss-goal',locked:'key-goal',freed:'people-goal',
  'all-free':'escort-goal',escort:'escort-goal','more-people':'people-goal',
  'group-aboard':'home-goal',victory:'complete',aboard:'boat',cellar:'cellar',
  'left-estate':'estate-goal'};
export function text(key,language='pl'){
  const row=rows[aliases[key]||key];return row?.[Math.max(0,languages.indexOf(language))]||key;
}
